# Generated by Django 5.2.4 on 2025-07-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='calendario.crop')),
            ],
            options={
                'unique_together': {('name', 'crop')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('plantios', models.JSONField(default=list)),
                ('colheitas', models.JSONField(default=list)),
                ('plantios_colheitas', models.JSONField(default=list)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='calendario.region')),
            ],
            options={
                'unique_together': {('name', 'region')},
            },
        ),
    ]
