site_name: AgroRenda
repo_url: https://github.com/FGA0138-MDS-Ajax/2025.1-Ingwaz/

theme: 
  name: material
  language: pt-BR
  palette: 
    - scheme: default
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-7 
        name: Modo escuro

    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Modo claro

nav:
  - Home: index.md
  - Documento de visão:
    - Visão Geral do Produto: visao/visao_produto.md
    - Visão Geral do Projeto: visao/visao_projeto.md
    - Processo de Desenvolvimento: visao/processo_desenvolvimento.md
    - Escopo do Projeto: visao/escopo_projeto.md
    - Métricas e Medições: visao/metricas_medicoes.md
    - Testes de Software: visao/teste.md
    - Referências: visao/referencias.md

  - Atas de reuniões:
    - Documentação e gestão de projeto: atas/ata1_definicoes.md
    - Kick Off: atas/ata2_kickoff.md
    - Alinhamento geral: atas/ata3_alinhamento_geral.md
    - Planejamento de funcionalidades: atas/ata4_planejamento_backlog.md
    - Definição final do produto: atas/ata5_documento_final_visao.md
    - Definição da arquitetura: atas/ata6_definicao_arq.md 
    - Documentação da arquitetura: atas/ata7_documentacao_arq.md
    
    - Atualização da documentação: atas/ata7.md
    - Acertos e correções de entregas: atas/ata8.md
    - Discussão sobre arquitetura: atas/ata9.md
    - Alinhamento: atas/ata10.md
    - Inicio da sprint 3: atas/ata11.md
    - Revisão da produção: atas/ata12.md 
    - Alinhamento de temas: atas/ata13.md
    - Atualização de novas sprints: atas/ata14.md

  - Arquitetura:
    - Introdução: arquitetura/introducao.md
    - Representação Arquitetural: arquitetura/representacao_arquitetural.md
    - Referências: arquitetura/referencias.md

markdown_extensions:
  - toc:
      title: Sumário

plugins:
  - search
  - macros

extra_css:
  - assets/css/home.css
  - assets/css/global.css
extra:
  team:
    - name: Arthur Moreira
      username: arthuurms
    - name: Camila Silva
      username: CamilaSilvaC
    - name: Carlos Henrique
      username: Carlos-UCH
    - name: Davi Leite
      username: WithyS2
    - name: Davi do Egito
      username: davi-egito
    - name: Geovanna Umbelino
      username: GeovannaUmbelino
    - name: Luísa de Souza
      username: luisa12ll
    - name: Marcos Vinícius
      username: MarcosViniciusG
    - name: Milena Marques
      username: milenamso
    - name: Pedro Teixeira
      username: PedroDev-sketch
    - name: Renan Pereira
      username: renanpr7
    - name: Yogi Nam 
      username: euyogi