# Generated by Django 5.2.3 on 2025-06-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=100)),
                ('data', models.DateField()),
                ('estimativa_colheita', models.DateField()),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='propriedade.propriedade')),
            ],
        ),
    ]
