# Generated by Django 5.2.3 on 2025-06-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantios', '0001_initial'),
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='propriedade.propriedade'),
        ),
    ]
