# Generated by Django 5.2.3 on 2025-06-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='applicant_info',
        ),
    ]
