# Generated by Django 5.2.3 on 2025-06-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credito', '0002_initial'),
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocredito',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_credito', to='propriedade.propriedade'),
        ),
    ]
