# Generated by Django 5.2.3 on 2025-06-25 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaocredito',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação de Crédito', 'verbose_name_plural': 'Solicitações de Crédito'},
        ),
        migrations.AddField(
            model_name='solicitacaocredito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocredito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitacaocredito',
            name='user',
            field=models.ForeignKey(default=1, help_text='Usuário que criou a solicitação de crédito.', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_credito_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocredito',
            name='score',
            field=models.FloatField(blank=True, help_text='Score de crédito gerado (0.0 a 1.0)', null=True),
        ),
    ]
