# Generated by Django 5.2.3 on 2025-07-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_alter_solicitacaocredito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocredito',
            name='finalidade',
            field=models.CharField(blank=True, help_text='Finalidade do crédito solicitado.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocredito',
            name='valor_solicitado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do crédito solicitado.', max_digits=10, null=True),
        ),
    ]
