# Generated by Django 5.2.3 on 2025-06-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_forecast', models.JSONField()),
                ('data_creation', models.DateTimeField(auto_now_add=True)),
                ('data_expiration', models.DateTimeField()),
                ('propriedade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='propriedade.propriedade')),
            ],
        ),
    ]
